modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory=true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory=true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[6.0.0,)"
ordering="NONE"
side="BOTH"
